[package]
name = "telebot"
version = "0.2.2"

authors = ["bytesnake <bytesnake@mailbox.org>"]
license = "MIT/Apache-2.0"
description = "A wrapper around the telegram bot api, powered by futures"

repository = "https://github.com/bytesnake/telebot"
readme = "README.md"
documentation = "https://docs.rs/telebot"

categories = ["network-programming"]
keywords = ["telebot", "telegram", "bot", "chat", "async"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
erased-serde = "0.3"
curl = "0.4.1"      
futures = "0.1.7"     
tokio-core = "0.1.2"
tokio-curl = "0.1.6"
uuid = { version = "0.2", features = ["v4"] }
telebot-derive = {version = "0.0.8", path = "./telebot-derive/"}
log = "0.3"
