[package]
name = "telebot"
version = "0.0.3"
authors = ["bytesnake <bytesnake@mailbox.org>"]
license = "MIT"
description = "A wrapper around the telegram bot api, powered by futures"

[dependencies]
serde = "0.8.20"
serde_json = "0.8"
serde_derive = "0.8.20"
curl = "0.4.1"      
futures = "0.1.7"     
tokio-core = "0.1.2"
tokio-curl = "0.1.6"
telebot-derive = "0.0.2"
