[package]
name = "telebot"
version = "0.2.5"

authors = ["bytesnake <bytesnake@mailbox.org>"]
license = "MIT/Apache-2.0"
description = "A wrapper around the telegram bot api, powered by futures"

repository = "https://github.com/bytesnake/telebot"
readme = "README.md"
documentation = "https://docs.rs/telebot"

categories = ["network-programming"]
keywords = ["telebot", "telegram", "bot", "chat", "async"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
erased-serde = "0.3"
futures = "0.1.7"     
tokio-core = "0.1.2"
hyper = "0.11.9"
hyper-tls = "0.1.2"
native-tls = "0.1"
hyper-multipart-rfc7578 = { git = "https://github.com/asonix/rust-hyper-multipart-rfc7578", branch = "asonix/in-memory-files" }
uuid = { version = "0.2", features = ["v4"] }
telebot-derive = {version = "0.0.9", path = "./telebot-derive/"}
log = "0.3"
